### ISSUE TITLE
How do I add http header when use OVCHTTPSessionManager?

### ISSUE THREAD

**Issue by rogeryu23** [Overcoat/Overcoat#100]
If i subclass the OVCHTTPSessionManager, how could I add the header like authorization header to it?

Thanks
Roger

**Comment by engineeringman** [comment]
This is done quite easily.  If you've ever used AFNetworking, it's done quite similarly.  Just write the following in your OVCHTTPSessionManager subclass's implementation:

```
+ (instancetype)manager
{
    static ServiceSessionManager *_sharedClient = nil;
    static dispatch_once_t onceToken;

    dispatch_once(&onceToken, ^{
      _sharedClient = [[ServiceSessionManager alloc] initWithBaseURL:[NSURL URLWithString:kApiSessionUrl]];
      _sharedClient.requestSerializer = [AFJSONRequestSerializer serializer];

      [_sharedClient.requestSerializer setValue:@"application/json" forHTTPHeaderField:@"Accept"];
    });
    return _sharedClient;
}
```

Note: I named my class `ServiceSessionManager`.

This example sets the value `application/json` for the header field `Accept`.

**Comment by sodastsai** [comment]
`Overcoat` is a wrapper to help developers convert response of `AFNetworking` to `Mantle` models.

So if you want to setup your request with more configuration like headers, you could set it as what you do while using AFNetworking.

Based on @engineeringman's answer _(btw, thanks your quick response :smile:)_, you could also extend `AFHTTPRequestSerializer` and override methods like `- [AFHTTPRequestSerializer requestWithMethod:URLString:parameters:error:]` to perform more setup.

**Comment by rogeryu23** [comment]
Great thanks
