### ISSUE TITLE
When deserialization fails, it fails silently with no error description.

### ISSUE THREAD

**Issue by engineeringman** [Overcoat/Overcoat#105]
In a previous project, an endpoint changed its date objects from an actual date object to a string containing the date object.  E.g. `"starts": 2015-07-07T00:00:00-06:00` changed to `"starts": "2015-07-07T00:00:00-06:00"`

Our only indication that something had happened was that our entire received response object was nil (eg OVCResponse.result), which caused a hard crash.  We had to dig through the Overcoat source before we realized it has absolutely no error handling for deserialization errors.
 
A simple solution would be changing the line `result = [valueTransformer transformedValue:result];` to use the Mantle transformer's method `transformedValue:success:error:` instead.

**Comment by sodastsai** [comment]
Hi @engineeringman 

Does #109 help solve this? :smile:

**Comment by engineeringman** [comment]
Neat!  That will certainly help us out!
