### ISSUE TITLE
duplicate interface definition for class 'OVCHTTPSessionManager'.

### ISSUE THREAD

**Issue by numerics** [Overcoat/Overcoat#106]
This created a problem for me: duplicate interface definition for class 'OVCHTTPSessionManager'... I'm stuck trying to fix this... any suggestions?

**Comment by sodastsai** [comment]
Hi
Would you like to provide more information like your Podfile lines mentioning about Overcoat, using Objective-C or Swift, and how you import Overcoat in the source code? Thanks.

**Comment by sodastsai** [comment]
Hi @numerics,

are you using `Overcoat` as another dependency of a `podspec` or using it directly in a `Podfile`?
Also, is `use_frameworks!` enabled?

**Comment by sodastsai** [comment]
if you're using Overcoat by the way I mentioned in last comment, `3.2.1` should fix this. :)

**Comment by sodastsai** [comment]
Ref: c17fe59
