### ISSUE TITLE
ReactiveCocoa 3.0+ support

### ISSUE THREAD

**Issue by startupthekid** [Overcoat/Overcoat#110]
I'd love to be able to use Overcoat with ReactiveCocoa Swift, are there any plans for the support?

**Comment by sodastsai** [comment]
Hi @startupthekid, I don't really use ReactiveCocoa, but I would try to add it to Overcoat. 
You're welcome to submit a PR for this too. :smile:

**Comment by startupthekid** [comment]
Overcoat already comes with RC as a submodule doesn't it? And maybe I will ;)

**Comment by sodastsai** [comment]
yup, but it was added by original project owner. 
I'm new owner since this summer. :)

But as you say, Overcoat has supported old version already, so it should not be too hard to convert it.

**Comment by startupthekid** [comment]
:+1:

**Comment by sodastsai** [comment]
notes for implementation: https://github.com/CocoaPods/CocoaPods/issues/4376

**Comment by sodastsai** [comment]
Tested. Dependency settings are updated by 7b16ac8 (Podspec)
