### ISSUE TITLE
Issue for mapping multiple objects inside the same path response

### ISSUE THREAD

**Issue by yreaction** [Overcoat/Overcoat#111]
Hello, after reading some of other solutions I finally end using :

+ (NSDictionary<NSString *,Class> *)responseClassesByResourcePath

I've create a OVCResponse:

+(NSString *)resultKeyPathForJSONDictionary:(NSDictionary *)JSONDictionary
{
    return @"data.user";
}

The problem is that it only model the user json response, I don't know how to achieve the result of modeling the "packs" array. I figured out that does not make sense to do a new OVCResponse for "packs" since it's an array of pack and its inside the same response.

+(NSString *)resultKeyPathForJSONDictionary:(NSDictionary *)JSONDictionary
{
    return @"data.packs";
}

The JSON response is (I've setup the model entities and MTLModel classes, User and Pack):

    data =     {
        packs =         (
                        {
                created = 1446056170;
                id = 208684;
                name = Aname;
                settings =                 {
                    isOpen = 1;
                };
                status =                 {
                    balance = 20000000;
                    bids = 0;
                    offers = 0;
                    points = 0;
                };
                type = normal;
                user =                 {
                    group = manager;
                    id = 848796;
                    name = yoquese;
                };
            }
        );
        user =         {
            checked = 0;
            created = 1446056119;
            email = "anEmail@email";
            id = 23412;
        };
        version = 100;
    };

Thanks in advance.

**Comment by sodastsai** [comment]
I have no quick idea about how to add this feature request into Overcoat now. Any suggestion? We may discuss about this :smile: 

A workaround would be create a new Mantle model class like:
```objective-c
@interface SomeAPIResultAdapter : MTLModel

// Remember to apply NSValueTransformers to convert dictionary result into instances of these 2 classes.
@property (nonatomic, strong, readonly) User *user;
@property (nonatomic, strong, readonly) NSArray<Pack *> *packs; 

@end
```

**Comment by sodastsai** [comment]
Same to #101
