### ISSUE TITLE
Failed to match deep path when there's a wild cast

### ISSUE THREAD

**Issue by lexrus** [Overcoat/Overcoat#112]
``` objective-c
+ (NSDictionary *) modelClassesByResourcePath
{
    return @{
    @"orders/delivery/range": [XWDeliveryRange class],
    @"orders/delivery/time": [XWShippingTime class],
    @"orders":               [XWOrder class],
    @"orders/*":             [XWOrder class]
    };
}
```

Then while doing a GET request to `orders/delivery/range` it always mismatched to [XWOrder class] because `orders/delivery` matches `orders/*` no matter how I change the line orders.

<img width="579" alt="screen shot 2015-11-05 at 6 51 18 pm" src="https://cloud.githubusercontent.com/assets/219689/10966442/8975cfbe-83ee-11e5-9da4-db01529b8823.png">

**Comment by lexrus** [comment]
Thank you for the rapid fix. Should I wait for a CocoaPods release or use the head version?

**Comment by sodastsai** [comment]
28aa171 should fix this issue. I sorted the children array by the type of matchers while the children array is changed. So it would match exact nodes first. (before *, **, and #)

There's also a test case for this: [-[OVCURLMatcherTests testWildcardAsFallback]](https://github.com/Overcoat/Overcoat/commit/2577e094651205bde5fa7436ad7f1b2166cced02#diff-c013db5dd5c5ba2a293eb5aa37c3ef86R112)

Another note is that, `NSDictionary` is not an ordered data structure. The execution/match order of switch-case syntax is also not ordered. so it's useless no matter how you change the line order.

To test this, use custom pod source first. Like
```ruby
pod 'Overcoat', :git => 'https://github.com/overcoat/overcoat.git'
```
