### ISSUE TITLE
Different Response Class depending on HTTP Response Code

### ISSUE THREAD

**Issue by lvandyk** [Overcoat/Overcoat#114]
Is it possible to map class X to 200 and class Y to 202 for the same resource path?

My scenario: /login either returns 200 with ouath token details or 202 with one time pin details.

**Comment by sodastsai** [comment]
Hi, we're also discussing about adding new features to the URL matcher.

I've proposed one in https://github.com/Overcoat/Overcoat/issues/64#issuecomment-154342881 which is used to return different classes by HTTP methods. Would it be okay that using similar way for HTTP status code?

**Comment by sodastsai** [comment]
Like:

```objective-c
+ (NSDictionary *)modelClassesByResourcePath {
    return @{
        @"model": [OVCTestModel class],
        @"path": [OVCURLMatcherNode nodeWithClassesByHTTPStatusCodes:@{
            @"*": [SomeModel class],
            @"204": [Some200Model class],
            @"201": [Some201Model class],
        }],
    };
}
```

**Comment by lvandyk** [comment]
This would be amazing! +1
