### ISSUE TITLE
Pod spec problems with PromiseKit

### ISSUE THREAD

**Issue by yreaction** [Overcoat/Overcoat#115]
I'm unable to satisfy the pod install/update for a objetive-c project

target 'something' do
    pod 'Overcoat/CoreData', '~> 3.0'
    pod 'Overcoat/PromiseKit', '~> 3.0'

[!] Pods written in Swift can only be integrated as frameworks; add `use_frameworks!` to your Podfile or target to opt into using it. The Swift Pod being used is: PromiseKit

**Comment by sodastsai** [comment]
Hi @yreaction 

As the error message says, `PromiseKit` is a `swift` pod. Hence you have to add `use_frameworks!` in your `Podfile`.  Like:
```ruby
use_frameworks!

target 'something' do
    pod 'Overcoat/CoreData', '~> 3.0'
    pod 'Overcoat/PromiseKit', '~> 3.0'
end
```

Or you could use `PromiseKit` 2.x which is an `Objective-C` pod. Like:
```ruby
target 'something' do
    pod 'Overcoat/CoreData', '~> 3.0'
    pod 'Overcoat/PromiseKit', '~> 3.0'
    pod 'PromiseKit`, '~> 2.0'  # Overcoat supports both 2.x and 3.x
end
```
