### ISSUE TITLE
Add acceptableContentTypes to OVCModelResponseSerializer?

### ISSUE THREAD

**Issue by bsameh** [Overcoat/Overcoat#116]
I'm trying to add acceptableContentTypes to the jsonSerializer so that I can parse text/html as JSON, I tried to subclass OVCModelResponseSerializer and use that custom serializer as the response serializer but it doesn't seem to work. Can Overcoat handle this?

**Comment by sodastsai** [comment]
Sure, I would expose related properties :)

**Comment by sodastsai** [comment]
This fix would be available in 4.0

**Comment by bsameh** [comment]
Thank you! I noticed how active you are and I must say I'm very impressed with Overcoat and the progress it's made since its release.

The thing is, I tried doing this myself (for now at least) and it doesn't seem to work. 

I noticed you're using AFJSONResponseSerializer by default (which makes sense, since you should be expecting JSON), however, overriding this doesn't seem to work. When I tried to do that with Overcoat, the mapping fails for some reason. Basically what I do is add text/html as an acceptableContentType by overriding the getter for jsonSerializer in my OVCModelResponseSerializer, I even tried changing OVCModelResponseSerializer itself but it still won't return a mapped response for some reason; resultClass is always nil. I checked my modelClassesByResourcePath and it's set up properly (supposedly). Am I doing something wrong?

Sorry if I'm asking for too much but I need to fix this on my end until 4.0 is release due to time limitations.

Again, amazing support by the way. :+1:

**Comment by sodastsai** [comment]
OK, I would check this again later. 

But it's so close to the holidays now. My full-time job is also busy. Hence I cannot promise you I would fix it in these days. (Sorry)

Anyway, if you have a solution on this, you're welcome to submit a PR, thanks.

**Comment by bsameh** [comment]
I've just pulled your changes from the master branch and it seems to be working fine. No need for you to waste more time on this.

Thank you!

**Comment by sodastsai** [comment]
:+1:
