### ISSUE TITLE
Failed to build 4.0.0-beta.1

### ISSUE THREAD

**Issue by lexrus** [Overcoat/Overcoat#117]
``` ruby
pod 'Overcoat', '~> 4.0.0-beta.1'
pod 'Overcoat/ReactiveCocoa', '~> 4.0.0-beta.1'
```

<img width="275" alt="screen shot 2015-12-24 at 11 18 03 am" src="https://cloud.githubusercontent.com/assets/219689/11988915/3cb31cf0-aa30-11e5-9871-717bc2666705.png">

I guess we should upgrade to ReactiveCocoa 4.

**Comment by sodastsai** [comment]
Sure. You could reference the Podfile for testing here https://github.com/Overcoat/Overcoat/blob/master/Podfile#L12.
