### ISSUE TITLE
Please upload new MTLManagedObject podspec

### ISSUE THREAD

**Issue by melbic** [Overcoat/Overcoat#122]
Because of this issue: https://github.com/Mantle/MTLManagedObjectAdapter/issues/18
An app using the MTLManagedObject Podspec can't be submitted.
In the Podspec i saw, that it points to your Fork. Could you please release a new version with just a different version string? I already prepared the Podspec here: 
https://gist.github.com/melbic/a549783df37a4af9ac7b
The only thing what differs is the version string.

**Comment by sodastsai** [comment]
Thanks: ) Updated. https://cocoapods.org/pods/MTLManagedObjectAdapter
