### ISSUE TITLE
Mantle and Overcoat

### ISSUE THREAD

**Issue by NorbertSzydlowski** [Overcoat/Overcoat#123]
Hi,
I am working with Overcoat 3.2.1.

I have got a lot of classes that work with this library and MantleSerializer.

I have got problem with one class, that CPU is 100% when I parse only id's.

With two different classes that contains the same fields, but have got different names, one of them have 100% cpu, but second is very fast loaded...

Any ideas?

events.class and lists_elements.class (100% CPU, app hanging)

**Comment by sodastsai** [comment]
Could you provide more information, like some sample code? thanks.
