### ISSUE TITLE
Do you need help with the 4.0 release?

### ISSUE THREAD

**Issue by codiophile** [Overcoat/Overcoat#126]
I see that 4.0 is currently in beta, but there is not a lot of activity in the repository lately. So I am wondering if there is anything I can do to help out with the release?

I might be starting a new project in a couple of weeks and I would like to be able to use a stable 4.0 version of Overcoat.

I've also seen that you are looking for maintainers and I might be interested in becoming a maintainer, since I have been using Overcoat for a while and I have been very happy with it.

**Comment by sodastsai** [comment]
sure. thanks. I've added you into the team.

I'm still quite busy in following weeks, but there seems to be some issues fired by others about 4.0. If those are not critical one, I think it's ok to release 4.0 now.
