### ISSUE TITLE
why can't overcoat auto map json key to properties?

### ISSUE THREAD

**Issue by walkerwzy** [Overcoat/Overcoat#130]
I can design the model exactly as the json response, e.g.

```
@implementation DMDoctor

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    return @{
//             @"consultScope": @"consultScope",
//             @"expertAcademicTitle": @"expertAcademicTitle",
//             @"expertFeature": @"expertFeature",
//             @"expertId": @"expertId",
//             @"expertName": @"expertName",
//             @"expertPhoto": @"expertPhoto",
//             @"expertSex": @"expertSex",
//             @"expertTechnicalTitle": @"expertTechnicalTitle",
//             @"expertWeight": @"expertWeight",
//             @"hospDeptId": @"hospDeptId",
//             @"hospDeptName": @"hospDeptName"
             };
}
```

see, all exactly the same . but I test by comment all fields, and all keys not being set.
if overcoat can act like [https://github.com/CoderMJLee/MJExtension](https://github.com/CoderMJLee/MJExtension), the work could be more easier (auto pair json key and class property), thus we only need to map some special keys but not always all the keys.

besides, if this is designed for developer can manually choose which keys are mapped, you can provide another map to exclude them. 

is it a good idea?

**Comment by grgcombs** [comment]
Would this be a safety/security concern though? Could it execute arbitrary code?  Certainly it would need to exclude known reserved keywords like "description" to avoid crashes if the JSON payload has those keys. 

I'd be inclined to keep an array of exact string matches

**Comment by walkerwzy** [comment]
yes, and I found it's the mantle thing... not should be done by overcoat
