### ISSUE TITLE
OVCManagedHTTPSessionManager.m creates backgroundContext, but never uses it.

### ISSUE THREAD

**Issue by jameshays** [Overcoat/Overcoat#131]
OVCManagedHTTPSessionManager.m creates backgroundContext, but never uses it.

I believe this line needs to be set

`managedObjectContext:self.backgroundContext];`

**Comment by grgcombs** [comment]
If you create a pull request Travis-CI can run through some unit tests

**Comment by sodastsai** [comment]
submit a PR, thanks 😄

**Comment by jameshays** [comment]
Done.

**Comment by grgcombs** [comment]
Thanks James! I merged and closed.
