### ISSUE TITLE
Dynamic/conditional object mapping

### ISSUE THREAD

**Issue by orenk86** [Overcoat/Overcoat#137]
Hi there, great work on this library!!

I have a tree of classes that inherit from each other, each with unique and non-unique fields. In some API requests I will have a mixed response of these objects, and I would like each one to be mapped accordingly.

For Example:
I have 2 classes - "Boy" and "Girl".
Both have a "gender" property, that can be either "male" or "female".
I want Overcoat to map each object in the response according to the value in the "gender" field. If "gender" equals "male" - map to the "Boy" class. If Gender equals "female", map to the "Girl" class.
That way I'll get a mixed response array with both "Boy" and "Girl" objects.

I hope I'm being clear enough.
Is there a way to do this in Overcoat?
Thanks!

**Comment by orenk86** [comment]
Solved!

I have mapped the routes to the "base object" class, and used the
`+ (Class)classForParsingJSONDictionary:(NSDictionary *)JSONDictionary`
method to perform the dynamic mapping.

**Comment by orenk86** [comment]
By the way @grgcombs , I have just read about your medical condition and procedure in another issue.
I wish you a successful procedure and a quick recovery!!

**Comment by grgcombs** [comment]
Thanks so much!  So far treatment is going well. Thanks for the well wishes!

G
