### ISSUE TITLE
Getting exception while using CoreData : An observer of NSManagedObjectContextDidSaveNotification illegally threw an exception

### ISSUE THREAD

**Issue by kikolobo** [Overcoat/Overcoat#67]
An observer of NSManagedObjectContextDidSaveNotification illegally threw an exception.  Objects saved = { } ....
and exception = Can only use -performBlock: on an NSManagedObjectContext that was created with a queue. with userInfo = (null)

Any idea what's causing this exception? It only comes to live when using core data...

Any help greatly appreciated!

**Comment by maimake** [comment]
me too! Had you solved it?

**Comment by maimake** [comment]
I found it !  
http://stackoverflow.com/questions/17649985/can-only-use-performblock-on-an-nsmanagedobjectcontext-that-was-created-with-a
