### ISSUE TITLE
duplicate NSManagedObject race condition

### ISSUE THREAD

**Issue by stefreak** [Overcoat/Overcoat#77]
I'm using mantles `propertyKeysForManagedObjectUniquing`.

The problem is that when having two requests ongoing in parallel where two instances of a specific MTLModel with the same identifier are mapped to an NSManagedObject, two instances with the same identifier end up in the core data store if they weren't there before at all.

I think this could be solved by putting `[MTLManagedObjectAdapter managedObjectFromModel:model insertingIntoContext:self.managedObjectContext]` into the `performBlockAndWait:` block, because it would lock the context for the other requests. (I'm talking about `OVCModelResponseSerializer saveResult:`).

Is there a specific reason the loop wasn't in the `performBlockAndWait` block? Would you be open for such a pull request?

Locally I've tested it and it works for me (I'm still testing a bit more though).

Thanks for Overcoat by the way, it's surprisingly simple and nice :)

**Comment by Gargam** [comment]
+1 for a merge of this PR

**Comment by sodastsai** [comment]
Hi, the PR #76 has been merged. And also the master is adopted with Mantle 2.0 support. Please test it with your projects and post feedback back, thanks.

To test with the master branch, you could change your `Podfile` into
* To use Overcoat with CoreData and Mantle 1.x
```ruby
pod 'Overcoat', :git => 'https://github.com/Overcoat/Overcoat.git', :branch => 'master'
```
* To use Overcoat with CoreData and Mantle 1.x
```ruby
pod 'Overcoat/CoreData', :git => 'https://github.com/Overcoat/Overcoat.git', :branch => 'master'
```
* To use Overcoat with CoreData and Mantle 2.x
```ruby
pod 'Overcoat/CoreData', :git => 'https://github.com/Overcoat/Overcoat.git', :branch => 'master'
pod 'MTLManagedObjectAdapter'
```

**Comment by stefreak** [comment]
@sodastsai tested it, and it seems to work :)

Why is the direct git reference to master branch necessary? Isn't this released yet?

**Comment by sodastsai** [comment]
@stefreak yup, I pushed it to Cocoapods's Spec repo just minutes ago. So now you can use it directly. :)
