### ISSUE TITLE
Mapping with wildcards in non-RESTfull paths

### ISSUE THREAD

**Issue by csilver** [Overcoat/Overcoat#80]
Hi, we were previously using older versions of Mantle (1.3.1) and Overcoat (1.2) and are attempting to upgrade.

Our url paths do not follow RESTful standards.  This was supported with Overcoat and Mantle for the older versions -- as we provided object mappings on a per-GET call basis --- but for the current version of Overcoat, it does not seem possible.  Since we currently are not able to change our url paths, is there any way at all for us to map paths similar to the one below, while supporting a * wildcard within the path? 

Or, optionally, is there still a way to map GET requests to an object type on a per request basis, as we were previously doing with the older Overcoat version? 

 (NSDictionary *)modelClassesByResourcePath {
+    return @{
+             @"models.(make.id=*).json": [CRModel class]
+                      };
+                      }

Thanks for any help!

**Comment by sodastsai** [comment]
So would the idea proposed in #55 match your requirements?
You're welcome to add more comments/ideas into that discussion threads :)
