### ISSUE TITLE
Mantle 2.0 support

### ISSUE THREAD

**Issue by sodastsai** [Overcoat/Overcoat#82]
is Overcoat compatible with Mantle 2.0?

**Comment by ryanmaxwell** [comment]
I'd too like to see an update with support for Mantle 2.0. I can fork and begin the upgrade, but I'd like to know if it's already proposed to save any duplicated effort

**Comment by gonzalezreal** [comment]
Unfortunately I don't have the time to work on Overcoat, as I am no longer using it in any project.
You're welcome propose any improvements, including Mantle 2.0 support.
I am also open to transfer ownership of the repo to an organization if there are people willing to contribute new features or improvements.

**Comment by sodastsai** [comment]
I think I would like to maintain this since my app, [Tickle](https://tickleapp.com) uses both `AFNetworking` and `Mantle`. Overcoat is great to save my time to bridge these 2 libraries.
But the question is that I'm not familiar with `CoreData`, `PromiseKit`, and `ReactiveCocoa`.

**Comment by eytanbiala** [comment]
@gonzalezreal I'd be happy to help maintain this project, if you'd like to add me as a collaborator.

**Comment by sodastsai** [comment]
any update on this?

**Comment by sodastsai** [comment]
Created a pull request for this: #87 

Original tests are passed. And I'm currently testing it with my project (on iOS 8 with Mantle 2.0).
This adoption should be work with both Mantle 1.5 and 2.0. And also with OS X and iOS.

**Comment by sodastsai** [comment]
closed by 40071d9
