### ISSUE TITLE
PromiseKit/Promise seems rename to PromiseKit/CorePromise

### ISSUE THREAD

**Issue by yuanyong** [Overcoat/Overcoat#96]
https://github.com/mxcl/PromiseKit/blob/master/PromiseKit.podspec

**Comment by sodastsai** [comment]
Hi, 

Overcoat doesn't support the newest PromiseKit (2.x) yet. You're welcome to submit a PR to make it. (Maybe check #85) (If possible, make both old version (1.x and not renamed one) and new version compatible)

**Comment by yuanyong** [comment]
@sodastsai Thanks for that, Expect @mxcl PR.

**Comment by mxcl** [comment]
All is ok though. Since overcoat still depends on 1.x.

**Comment by sodastsai** [comment]
Hi guys, I've pushed a commit f444f00 which use PromiseKit 2.x as dependency. I'd glad to invite you to test it :)

```ruby
pod 'Overcoat/PromiseKit', :git => 'https://github.com/Overcoat/Overcoat.git', :branch => 'master'
```
