### ISSUE TITLE
support IOS6

### ISSUE THREAD

**Issue by ranshon** [Overcoat/Overcoat#98]
use  OVCHTTPRequestOperationManager  but catch the error  . +[NSCharacterSet URLQueryAllowedCharacterSet]: unrecognized selector sent to clas

**Comment by sodastsai** [comment]
Overcoat doesn't use this API call. (`+[NSCharacterSet URLQueryAllowedCharacterSet]`).

But if you're using `AFNetworking 2.6` which is just released last week, they do use this method in [`AFNetworking/AFURLRequestSerialization.m`](https://github.com/AFNetworking/AFNetworking/blob/2cf77adec15defd070873a06b6283dfedc8c4df1/AFNetworking/AFURLRequestSerialization.m#L80). _(And they are planned to drop off the support of iOS 6.0)_
