### ISSUE TITLE
OVCHTTPRequestOperationManager don't find in version 3.1

### ISSUE THREAD

**Issue by NorbertSzydlowski** [Overcoat/Overcoat#99]

**Comment by sodastsai** [comment]
Hi Nobert,

could you attach more information like the error message generated by Xcode or lines about Overcoat in the Podfile you're using? Thanks.

**Comment by NorbertSzydlowski** [comment]
I have got   s.dependency 'Overcoat', '~>3.0' in .podspec file.
"Cannot find interface declaration for 'OVCHTTPRequestOperationManager', superclass of ...

**Comment by tflhyl** [comment]
I solve it by adding 
`s.pod_target_xcconfig = { GCC_PREPROCESSOR_DEFINITIONS' => 'OVERCOAT_SUPPORT_URL_SESSION=1                         OVERCOAT_SUPPORT_URL_CONNECTION=1'}`
on my podspec. 

im not sure if there is better solution for this. it will be nice if these preprocessor flags are set automatically on our pod when we depends on Overcoat

**Comment by sodastsai** [comment]
oh, I see. This is because you're using it as a dependency of another pod package. (Instead of using like `pod 'Overcoat'). I never tested this before, so I've created another issue (#103) for testing this in the future.

Thanks.

**Comment by tflhyl** [comment]
Thanks @sodastsai
